"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Save, UserRound } from "lucide-react";
import AppShell from "@/components/AppShell";
import { getProfile, saveProfile, type Profile } from "@/lib/data/store";
import { defaultProfile } from "@/lib/data/program";

export default function SettingsPage(){const [p,setP]=useState<Profile>(defaultProfile);const [saved,setSaved]=useState(false);useEffect(()=>{getProfile().then(setP)},[]);async function save(){await saveProfile(p);setSaved(true);setTimeout(()=>setSaved(false),1800)};return <AppShell><main className="page"><div className="container"><div className="hero-row"><div><div className="eyebrow">Профиль</div><h1>Настройки</h1><p className="lead">Эти параметры определяют день программы и цели на главном экране.</p></div><button className="btn" onClick={save}><Save size={17}/>{saved?"Сохранено":"Сохранить"}</button></div><div className="split"><section className="card"><div className="form-grid"><label className="field"><span>Имя</span><input className="input" value={p.display_name} onChange={e=>setP({...p,display_name:e.target.value})}/></label><label className="field"><span>Дата старта</span><input className="input" type="date" value={p.start_date} onChange={e=>setP({...p,start_date:e.target.value})}/></label><label className="field"><span>Рост, см</span><input className="input" inputMode="decimal" value={p.height_cm} onChange={e=>setP({...p,height_cm:Number(e.target.value)})}/></label><label className="field"><span>Стартовый вес, кг</span><input className="input" inputMode="decimal" value={p.start_weight_kg} onChange={e=>setP({...p,start_weight_kg:Number(e.target.value)})}/></label><label className="field"><span>Целевой вес, кг</span><input className="input" inputMode="decimal" value={p.target_weight_kg} onChange={e=>setP({...p,target_weight_kg:Number(e.target.value)})}/></label><label className="field"><span>Калории</span><input className="input" inputMode="numeric" value={p.calories_target} onChange={e=>setP({...p,calories_target:Number(e.target.value)})}/></label><label className="field"><span>Белок, г</span><input className="input" inputMode="numeric" value={p.protein_target_g} onChange={e=>setP({...p,protein_target_g:Number(e.target.value)})}/></label><label className="field"><span>Вода, л</span><input className="input" inputMode="decimal" value={p.water_target_l} onChange={e=>setP({...p,water_target_l:Number(e.target.value)})}/></label><label className="field"><span>Цель шагов</span><input className="input" inputMode="numeric" value={p.steps_target} onChange={e=>setP({...p,steps_target:Number(e.target.value)})}/></label></div></section><aside className="card sticky"><UserRound size={28} color="var(--accent)"/><h2 style={{marginTop:16}}>Аккаунт</h2><p className="meal-desc">Без Supabase приложение автоматически работает локально. После настройки переменных окружения можно войти и синхронизировать новые записи через облако.</p><Link href="/login" className="btn secondary full">Войти / зарегистрироваться</Link><p className="install-hint" style={{marginTop:16}}>На iPhone: Safari → Поделиться → «На экран Домой». После деплоя приложение откроется без интерфейса браузера.</p></aside></div></div></main></AppShell>}
